### PR TITLE
Fix proxy

### LINKED ISSUE #616: Fix using yo behind a proxy on Node versions >= 11.6.0
## Type of issue

Bug

## What happens

Running `yo` fails when using a system Proxy since Node.js `11.6.0`.

## Background

We are using [global-tunnel-ng](https://github.com/np-maintain/global-tunnel) to make it possible to use yo behind a proxy. This was implemented in https://github.com/yeoman/yo/pull/573.

Sadly `global-tunnel-ng`is broken since Node.js `11.6.0` and [according](https://gitter.im/yeoman/yeoman?at=5cc4c9e63d78aa6c03a7065c) to one of the contributors it probably won’t support newer Node versions in the future.

## How to fix this

Switch from using `global-tunnel-ng` to [global-agent](https://github.com/gajus/global-agent):

1. Change the global-tunnel initialization at the entry of the [yo cli](https://github.com/yeoman/yo/blob/932ef07104b81de32fa3f0f6c9c2df61f4f0d9e6/lib/cli.js#L20) and [yo doctor](https://github.com/yeoman/doctor/blob/3a3689c2d88ff1c1233e728313a38e6c4edaaec0/lib/cli.js#L6) according https://github.com/gajus/global-agent/blob/master/README.md#usage should do the trick
1. Adding a note in the documentation would help, mainly because global-agent uses the environment variable GLOBAL_AGENT_HTTP_PROXY instead of the traditional HTTP_PROXY. Keep in mind global-agent does not look for a proxy in the npm configuration and may not support all the different kinds of proxy connections.

## How to test this

This should be testable using a local proxy like [Burp Proxy ](https://portswigger.net/burp), [Charles](https://www.charlesproxy.com/) or [mitmproxy](https://mitmproxy.org/).

## Who could help with this

@gajus, the maintainer of 'global-agent' was so kind to offer his help in the [Yeoman Chat](https://gitter.im/yeoman/yeoman?at=5cc70b3e3d78aa6c03b5da9a) 💖

### LINKED ISSUE #620: TypeError: Cannot read property 'proxy' of undefined
## Bug

When running `npx -p yo -p @custom/generator-custom-app -c 'yo @custom/custom-app`, an error `TypeError: Cannot read property 'proxy' of undefined` occurs.

## My environment

* *OS version/details*: `macOS 10.14.5`
* *Node version:* `v12.4.0` 
* *npm version:* `6.9.0` 
* *Version of yo :* `2.0.6` 

## Expected behavior

Yeoman not to encounter `TypeError: Cannot read property 'proxy' of undefined`

## Current behavior

Yeoman encounters `TypeError: Cannot read property 'proxy' of undefined`:

```
TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:116:13)
    at TunnelingAgent.request (http.js:44:10)
    at TunnelingAgent.createSocket (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:126:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:207:41)
    at TunnelingAgent.addRequest (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/tunnel/lib/tunnel.js:84:8)
    at new ClientRequest (_http_client.js:276:16)
    at Object.request (https.js:309:10)
    at Object.request (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/index.js:336:40)
    at get (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/latest-version/node_modules/got/index.js:33:18)
(node:29391) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (/Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/each-async/node_modules/onetime/index.js:15:11)
    at /Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:23:7
    at /Users/P781555/.npm/_npx/29063/lib/node_modules/yo/node_modules/yeoman-doctor/lib/rules/yo-version.js:21:23
(node:29391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:29391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## Steps to reproduce the behavior

Not easy to replicate (using private NPM repository with a custom generator). But the error seems to happen in this line:

```
mixinProxying(this, opts.proxy);
```

of `.npm/_npx/29063/lib/node_modules/yo/node_modules/global-tunnel-ng/lib/agents.js`:

```
/* jshint node:true */
'use strict';

var util = require('util');
var http = require('http');
var HttpAgent = http.Agent;
var https = require('https');
var HttpsAgent = https.Agent;

var pick = require('lodash/pick');

/**
 * Proxy some traffic over HTTP.
 */
function OuterHttpAgent(opts) {
  HttpAgent.call(this, opts);
  mixinProxying(this, opts.proxy);
}
util.inherits(OuterHttpAgent, HttpAgent);
exports.OuterHttpAgent = OuterHttpAgent;

/**
 * Proxy some traffic over HTTPS.
 */
function OuterHttpsAgent(opts) {
  HttpsAgent.call(this, opts);
  mixinProxying(this, opts.proxy);
}
util.inherits(OuterHttpsAgent, HttpsAgent);
exports.OuterHttpsAgent = OuterHttpsAgent;

/**
 * Override createConnection and addRequest methods on the supplied agent.
 * http.Agent and https.Agent will set up createConnection in the constructor.
 */
function mixinProxying(agent, proxyOpts) {
  agent.proxy = proxyOpts;

  var orig = pick(agent, 'createConnection', 'addRequest');

  // Make the tcp or tls connection go to the proxy, ignoring the
  // destination host:port arguments.
  agent.createConnection = function(port, host, options) {
    return orig.createConnection.call(this, this.proxy.port, this.proxy.host, options);
  };

  agent.addRequest = function(req, options) {
    req.path =
      this.proxy.innerProtocol + '//' + options.host + ':' + options.port + req.path;
    return orig.addRequest.call(this, req, options);
  };
}
```

### PR DESCRIPTION
**Pull request by LitoMore**
Resolve #616 
Fix #620

### CODE REVIEW

**Comment by SBoudrias** [comment]
Woot I'll cut a release soon!

File: lib/cli.js [hunk 1]
```diff
@@ -17,7 +17,15 @@ const Router = require('./router');
 const gens = list(process.argv.slice(2));
 
 // Override http networking to go through a proxy ifone is configured
-require('global-tunnel-ng').initialize();
+const MAJOR_NODEJS_VERSION = parseInt(process.version.slice(1).split('.')[0], 10);
+
+if (MAJOR_NODEJS_VERSION >= 10) {
+  // `global-agent` works with Node.js v10 and above.
+  require('global-agent').bootstrap();
```
Comment (gajus) [inline lib/cli.js]: If you are not using `global` variables, then using [`createGlobalProxyAgent`](https://github.com/gajus/global-agent#setup-proxy-using-createglobalproxyagent) would be more appropriate.

You might also want to configure [`environmentVariableNamespace`](https://github.com/gajus/global-agent#createglobalproxyagent).

**Comment by tristanwagner** [comment]
with yo using `global-agent` I can't define a custom https agent unless I specify the env variable `GLOBAL_AGENT_FORCE_GLOBAL_AGENT=false` which is kinda annoying to be honest
