### PR TITLE
Fix #284: wrong generators display

### LINKED ISSUE #284: It is a strange display of "yeoman generator" list.
yo@1.4.4, it is a strange display of "yeoman generator" list. Sometimes sub generator is displayed to other generators.

```
$ yo --version
1.4.4
$ npm install -g generator-webapp
$  yo --help
Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist

Available Generators:
  webapp
  mocha
$ yo --help
Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist

Available Generators:
  angular-fullstack
    controller
    decorator
    directive
    endpoint
    factory
    filter
    heroku
    openshift
    provider
    route
    service
  webapp
    constant
    deploy
    value
    view
  mocha
$ npm uninstall -g generator-webapp generator-mocha
$ yo --help
Usage: yo GENERATOR [args] [options]

General options:
  -h, --help     # Print generator's options and usage
  -f, --force    # Overwrite files that already exist

Available Generators:
  angular-fullstack
    controller
    decorator
    directive
    endpoint
    factory
    filter
    heroku
    openshift
    provider
    route
    service
    constant
    deploy
    value
    view
```

`constant`, `deploy`, `value` and `view` I thing of angular-fullstack, it is displayed in the webapp.

### PR DESCRIPTION
**Pull request by pauldijou**
Problem was from displaying sub-generators in alphabetical order and displaying the generator name when finding the `app` sub-generator (the default one). Since `app` is often the first alphabetical sub-generator, it didn't shown on most generators.

Anyway, the code is a bit verbose but doesn't rely on any alphabetical order anymore.

### CODE REVIEW

**Comment by sindresorhus** [comment]
//@CExMAllen

File: lib/cli.js [hunk 1]
```diff
@@ -78,10 +78,23 @@ function init() {
     // start the interactive UI if no generator is passed
     if (!cmd) {
       if (opts.help) {
-        var genList = Object.keys(env.getGeneratorsMeta()).map(function (el) {
-          var parts = el.split(':');
-          var first = parts.shift();
-          return '  ' + (parts[0] === 'app' ? first : '  ' + parts.join(':'));
+        var generators = Object.keys(env.getGeneratorsMeta()).reduce(function (acc, gen) {
```
Comment (SBoudrias) [inline lib/cli.js]: Can we have better variable names here. What does `acc` stand for?

File: lib/cli.js [hunk 2]
```diff
@@ -78,10 +78,23 @@ function init() {
     // start the interactive UI if no generator is passed
     if (!cmd) {
       if (opts.help) {
```
Comment (SBoudrias) [inline lib/cli.js]: All this block should go into a function. e.g.:

```js
var generatorList = createGeneratorList(env.getGeneratorsMeta());
console.log(generatorList);
```

This would also allow us to add unit tests validating the fix is working correctly.

File: lib/cli.js [hunk 3]
```diff
@@ -78,10 +78,23 @@ function init() {
...
+          // If sub-generator (!== app), save it
+          if (parts[0] !== 'app') {
+            acc[genName].push(parts.join(':'));
+          }
+
+          return acc;
+        }, {});
+
+        var genList = Object.keys(generators).map(function (gen) {
+          return '  ' + gen + '\n' + generators[gen].map(function (sub) { return '    '+sub; }).join('\n');
```
Comment (SBoudrias) [inline lib/cli.js]: Move this on multiple line.

Also, always add spaces between operators (in this case before and after `+`).

**Comment by pauldijou** [comment]
@SBoudrias Done

**Comment by SBoudrias** [comment]
Any chance you could add a test?

**Comment by sindresorhus** [comment]
@SBoudrias Shouldn't this go into [`yeoman-generator`](https://github.com/yeoman/generator)?

**Comment by SBoudrias** [comment]
I don't think so, it is very much coupled to the idea of displaying something on the command line. `yo` looks like the appropriate place for me.

Maybe yeoman/environment should returns more easily parseable data. But this is something we can consider later on. Also, from the core system perspective, there's no such things as sub-generators. Everything is a top level generator, so I'm not even convinced the answer yeoman/environment returns should change... Either way, my point was this would require a discussion and I don't think we should delay fixing this bug on a semantic conversation :)

**Comment by sindresorhus** [comment]
ok

**Comment by SBoudrias** [comment]
@pauldijou Hey, just a ping about the tests. Any plans to get this ready?

**Comment by pauldijou** [comment]
@SBoudrias My bad, I forgot about that... I give it a try today but I'm not sure how to test it. The result depends on which generators are actually installed when testing. I tried to mock it using mockery but totally failed. Also, I'm not sure if it would be better to test the full output of the help flag or only the available generators list.

**Comment by SBoudrias** [comment]
I'll merge as is to provide the fix.
